# Generated by Django 5.2.7 on 2025-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moissonneur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeudedonnees',
            name='titre',
            field=models.CharField(max_length=1024, verbose_name='Titre du jeu de données'),
        ),
    ]
